language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  include:
      env:
        - TEST_COVERAGE=true

before_install:
  - phpenv config-rm xdebug.ini
  - pecl install pcov
  - composer self-update

install:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - composer global require infection/infection
  - composer install --no-progress --no-interaction --no-ansi --prefer-dist --no-suggest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [[ "$TEST_COVERAGE" == 'true' ]]; then ./cc-test-reporter before-build ; fi

script:
  - mkdir ./coverage
  - composer run-script test -- --colors=always --coverage-clover ./coverage/clover.xml --coverage-xml=./coverage/coverage-xml --log-junit=./coverage/junit.xml
  - composer run-script analyse -- --no-progress
  - composer run-script cs-check
  - infection --min-msi=75 --min-covered-msi=80 --threads=$(nproc) --coverage=coverage

after_script:
  - |
    if [[ $TEST_COVERAGE == 'true' && $TRAVIS_TEST_RESULT == 0 ]]; then
      echo "Uploading coverage...";
      ./cc-test-reporter format-coverage -t clover -o ./coverage/cc.json ./coverage/clover.xml;
      ./cc-test-reporter upload-coverage -i ./coverage/cc.json;
    fi
